spring:
  application:
    name: inventory-manager-api
  profiles:
    active: dev

  # ============ DATABASE CONFIGURATION ===================
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:h2:mem:inventorydb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # ============ KAFKA CONFIGURATION ===================
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: inventory-service-group
      auto-offset-reset: earliest
    listener:
      retry-template:
        retry:
          max-attempts: 3

# ============ CUSTOM APP CONFIGURATION ===================
app:
  kafka:
    topic:
      stock-updates: stock-updates-topic
      stock-updates-dlq: stock-updates-topic.DLT